fix pip install error
datajoint/intanrhsreader pull request #2
Opened 2023-02-22 16:19 UTC by JaerongA

- fixed an error in importing the module.
- updated Readme.
- added `.gitignore` to ignore .egg-info after installation.

2023-02-22 16:25 UTC, kabilar commented on .gitignore
> +#.idea/
Thanks @JaerongA.  What repo is this `.gitignore` based off of?  Should we use the `.gitignore` that we have been using for the Elements?

2023-02-22 16:26 UTC, kabilar requested changes
Thanks @JaerongA.  One question above.

2023-02-22 16:30 UTC, tdincer commented
I don't think this PR is necessary. The file is not needed to be in a module.

2023-02-22 16:34 UTC, tdincer commented
@kabilar Could you try to install the repo and import the load_file? I don't experience the bug.

2023-02-22 16:40 UTC, JaerongA commented
> I don't think this PR is necessary. The file is not needed to be in a module.

hmm encountering this error after installation.

![image](https://user-images.githubusercontent.com/55012592/220696067-7c5c5723-34f2-4dd1-bb38-eaf169ce1255.png)

2023-02-22 16:41 UTC, tdincer commented
> > I don't think this PR is necessary. The file is not needed to be in a module.
> 
> hmm encountering this error after installation.
> 
> ![image](https://user-images.githubusercontent.com/55012592/220696067-7c5c5723-34f2-4dd1-bb38-eaf169ce1255.png)

Could you try loading the package in a different terminal? I'm just trying to understand the nature of the bug.

2023-02-22 16:43 UTC, JaerongA commented on .gitignore
> +#.idea/
@kabilar  I took it from here [https://github.com/github/gitignore/blob/main/Python.gitignore](url)  but yes, it makes sense to use one from element-repo

2023-02-22 20:11 UTC, tdincer commented
@kabilar @JaerongA  I don't understand why this is not a bug on my machine. After you guys resolve the `.gitignore` conflict, let's merge this PR. Chris also couldn't import the function.

2023-02-24 22:24 UTC, tdincer approved these changes

2023-02-24 22:24 UTC, merged